line-length = 120
target-version = "py311"

exclude = [
    "googleTtsForNvda/synthDrivers/googleTtsForNvda/websocketClientRepo",
    "googleTtsForNvda/synthDrivers/googleTtsForNvda/WasmTtsEngine",
    "googleTtsForNvda/synthDrivers/googleTtsForNvda/cld2",
    "googleTtsForNvda/synthDrivers/googleTtsForNvda/web",
]

builtins = ["_", "ngettext", "pgettext", "npgettext"]

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM"]
ignore = ["W191", "E101", "E501", "UP035", "SIM102", "B904"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
